name: Deploy FastAPI (Dev) to Azure

on:
  push:
    branches:
      - dev   # 🚀 Trigger only when pushing to dev branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: |
          echo "No tests yet for dev"

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp (Dev)
        uses: azure/webapps-deploy@v2
        with:
          app-name: "py-fastapi-dev"   # ⚡ replace with your Dev App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_DEV_PUBLISH_PROFILE }}
          package: release.zip